plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Nutmeg.social
description: Nutmeg.social Hub is an informational site tied to Nutmeg.social, a regional Mastodon instance for Connecticut
lang: en
locale: en_US
url: "https://hub.nutmeg.social"
git_web_base: https://github.com/nutmegsocial/hub/blob/HEAD/
baseurl: ""
permalink: "/:title"

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
